package compilateur.ARMGenerator;

import compilateur.ast.Affectation;
import compilateur.ast.Bloc;
import compilateur.ast.CharNode;
import compilateur.ast.DeclFctInt;
import compilateur.ast.DeclFctStruct;
import compilateur.ast.DeclVarInt;
import compilateur.ast.DeclVarStruct;
import compilateur.ast.Decl_typ;
import compilateur.ast.Different;
import compilateur.ast.Division;
import compilateur.ast.Egal;
import compilateur.ast.Expr_et;
import compilateur.ast.Expr_ou;
import compilateur.ast.Fichier;
import compilateur.ast.Fleche;
import compilateur.ast.Idf;
import compilateur.ast.IdfParenthesis;
import compilateur.ast.IdfParenthesisEmpty;
import compilateur.ast.IfThen;
import compilateur.ast.IfThenElse;
import compilateur.ast.Inferieur;
import compilateur.ast.InferieurEgal;
import compilateur.ast.IntNode;
import compilateur.ast.Minus;
import compilateur.ast.MoinsUnaire;
import compilateur.ast.Multiplication;
import compilateur.ast.Negation;
import compilateur.ast.ParamInt;
import compilateur.ast.ParamListMulti;
import compilateur.ast.ParamStruct;
import compilateur.ast.Plus;
import compilateur.ast.Return;
import compilateur.ast.Semicolon;
import compilateur.ast.Sizeof;
import compilateur.ast.Superieur;
import compilateur.ast.SuperieurEgal;
import compilateur.ast.While;


public interface ARMVisitor<T>{

    public T visit(Fichier fichier);
    public T visit(Idf idf);
    public T visit(DeclVarInt declVarInt);
    public T visit(DeclVarStruct declVarStruct);
    public T visit(Decl_typ decl_typ);
    public T visit(DeclFctInt declFctInt);
    public T visit(DeclFctStruct declFctStruct);
    public T visit(ParamListMulti paramListMulti);
    public T visit(ParamInt paramInt);
    public T visit(ParamStruct paramStruct);
    public T visit(Sizeof sizeof);
    public T visit(IdfParenthesis idfParenthesis);
    public T visit(IdfParenthesisEmpty idfParenthesisEmpty);
    public T visit(IfThen ifThen);
    public T visit(IfThenElse ifThenElse);
    public T visit(While while1);
    public T visit(Return return1);
    public T visit(Bloc bloc);
    public T visit(CharNode charNode);
    public T visit(IntNode intNode);
    public T visit(Affectation affectation);
    public T visit(Fleche fleche);
    public T visit(MoinsUnaire unaire);
    public T visit(Negation unaire);
    public T visit(Semicolon semicolon);
    public T visit(Expr_ou expr_ou);
    public T visit(Expr_et expr_et);
    public T visit(Egal egal);
    public T visit(Different dif);
    public T visit(Inferieur inf);
    public T visit (InferieurEgal infEgal);
    public T visit (Superieur sup);
    public T visit (SuperieurEgal supEgal);
    public T visit (Plus plus);
    public T visit (Minus minus);
    public T visit (Division div);
    public T visit (Multiplication mult);
    
}
