package compilateur.TDS;

import compilateur.ast.Affectation;
import compilateur.ast.Bloc;
import compilateur.ast.CharNode;
import compilateur.ast.DeclFctInt;
import compilateur.ast.DeclFctStruct;
import compilateur.ast.DeclVarInt;
import compilateur.ast.DeclVarStruct;
import compilateur.ast.Decl_typ;
import compilateur.ast.Different;
import compilateur.ast.Division;
import compilateur.ast.Egal;
import compilateur.ast.Expr_et;
import compilateur.ast.Expr_ou;
import compilateur.ast.Fichier;
import compilateur.ast.Fleche;
import compilateur.ast.Idf;
import compilateur.ast.IdfParenthesis;
import compilateur.ast.IdfParenthesisEmpty;
import compilateur.ast.IfThen;
import compilateur.ast.IfThenElse;
import compilateur.ast.Inferieur;
import compilateur.ast.InferieurEgal;
import compilateur.ast.IntNode;
import compilateur.ast.Minus;
import compilateur.ast.Multiplication;
import compilateur.ast.ParamInt;
import compilateur.ast.ParamListMulti;
import compilateur.ast.ParamStruct;
import compilateur.ast.Plus;
import compilateur.ast.Return;
import compilateur.ast.Semicolon;
import compilateur.ast.Sizeof;
import compilateur.ast.Superieur;
import compilateur.ast.SuperieurEgal;
import compilateur.ast.MoinsUnaire;
import compilateur.ast.Negation;
import compilateur.ast.While;


public interface TdsVisitor{

    public void visit(Fichier fichier, Tds tds);
    public void visit(Idf idf, Tds tds);
    public void visit(DeclVarInt declVarInt, Tds tds);
    public void visit(DeclVarStruct declVarStruct, Tds tds);
    public void visit(Decl_typ decl_typ, Tds tds);
    public void visit(DeclFctInt declFctInt, Tds tds);
    public void visit(DeclFctStruct declFctStruct, Tds tds);
    public void visit(ParamListMulti paramListMulti, Tds tds);
    public void visit(ParamInt paramInt, Tds tds);
    public void visit(ParamStruct paramStruct, Tds tds);
    public void visit(Sizeof sizeof, Tds tds);
    public void visit(IdfParenthesis idfParenthesis, Tds tds);
    public void visit(IdfParenthesisEmpty idfParenthesisEmpty, Tds tds);
    public void visit(IfThen ifThen, Tds tds);
    public void visit(IfThenElse ifThenElse, Tds tds);
    public void visit(While while1, Tds tds);
    public void visit(Return return1, Tds tds);
    public void visit(Bloc bloc, Tds tds);
    public void visit(CharNode charNode, Tds tds);
    public void visit(IntNode intNode, Tds tds);
    public void visit(Affectation affectation, Tds tds);
    public void visit(Expr_ou expr_ou, Tds tds);
    public void visit(Expr_et expr_et, Tds tds);
    public void visit(Egal egal, Tds tds);
    public void visit(Different dif, Tds tds);
    public void visit(Inferieur inf, Tds tds);
    public void visit(InferieurEgal infEgal, Tds tds);
    public void visit(Superieur sup, Tds tds);
    public void visit(SuperieurEgal supEgal, Tds tds);
    public void visit(Plus plus, Tds tds);
    public void visit(Minus minus, Tds tds);
    public void visit(Division div, Tds tds);
    public void visit(Multiplication mult, Tds tds);
    public void visit(Fleche fleche, Tds tds);
    public void visit(MoinsUnaire unaire, Tds tds);
    public void visit(Negation unaire, Tds tds);
    public void visit(Semicolon semicolon, Tds tds);
    
}
